individual_augmentations:
  - name: ColorJitter
    params:
      p: 1
  - name: Blur
    params:
      p: 1
multiple_augmentations:
  - name: ColorJitter
    params:
      p: 1
  - name: Blur
    params:
      p: 1
